behaviors:
  Combiner:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 64
    max_steps: 2000000
    keep_checkpoints: 5
    checkpoint_interval: 100000
    threaded: true
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 64
      buffer_size: 10240
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
environment_parameters:
  void_ratio:
    curriculum:
      - name: FirstLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 100
          #require_reset: true
        value: 0.40
      - name: SecondLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 200
        value: 0.30
      - name: ThirdLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 200
        value: 0.25
      - name: FourthLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 200
        value: 0.20
      - name: FifthLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 200
        value: 0.15
      - name: SixthLesson
        completion_criteria:
          measure: reward
          behavior: Combiner
          threshold: 0.8
          min_lesson_length: 200
        value: 0.1
      - name: LastLesson
        value: 0.05